server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false

spring:
  cloud:
    gateway:
      default-filters:
      - name: KeyIdAuthentication
      - name: ServiceToServiceAuthentication
      routes:

### auth ###

      - id: v1_set_roles
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/set-roles
        - Method=POST
        filters:
        - RewritePath=/api/v1/set-roles, /v1-set-roles

### gym ###

      - id: v1_gym_cud_gym
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/gym, /v1-gym-crud-gym
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v1_gym_cud_contacts
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/contacts
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/gym/contacts, /v1-gym-crud-contacts
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v1_gym_cud_addresses
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/addresses
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/gym/addresses, /v1-gym-crud-addresses
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v1_gym_cud_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/events
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/gym/events, /v1-gym-crud-events
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v1_gym_cud_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/subscription-plans
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/gym/subscription-plans, /v1-gym-crud-subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v1_gym_read_gym
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym
        - Method=GET
        filters:
        - RewritePath=/api/v1/gym, /v1-gym-crud-gym
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v1_gym_read_contacts
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/contacts
        - Method=GET
        filters:
        - RewritePath=/api/v1/gym/contacts, /v1-gym-crud-contacts
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v1_gym_read_addresses
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/addresses
        - Method=GET
        filters:
        - RewritePath=/api/v1/gym/addresses, /v1-gym-crud-addresses
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v1_gym_read_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/events
        - Method=GET
        filters:
        - RewritePath=/api/v1/gym/events, /v1-gym-crud-events
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v1_gym_read_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/subscription-plans
        - Method=GET
        filters:
        - RewritePath=/api/v1/gym/subscription-plans, /v1-gym-crud-subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### personal trainer ###

      - id: v1_personal_trainer_cud_personal-trainer
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/personal-trainer, /v1-personal-trainer-crud-personal-trainer
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v1_personal_trainer_cud_contacts
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer/contacts
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/personal-trainer/contacts, /v1-personal-trainer-crud-contacts
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v1_personal_trainer_cud_addresses
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer/addresses
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/personal-trainer/addresses, /v1-personal-trainer-crud-addresses
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v1_personal_trainer_cud_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer/events
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/personal-trainer/events, /v1-personal-trainer-crud-events
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v1_personal_trainer_cud_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer/subscription-plans
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/personal-trainer/subscription-plans, /v1-personal-trainer-crud-subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v1_personal_trainer_read_personal-trainer
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer
        - Method=GET
        filters:
        - RewritePath=/api/v1/personal-trainer, /v1-personal-trainer-crud-personal-trainer
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v1_personal_trainer_read_contacts
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer/contacts
        - Method=GET
        filters:
        - RewritePath=/api/v1/personal-trainer/contacts, /v1-personal-trainer-crud-contacts
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v1_personal_trainer_read_addresses
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer/addresses
        - Method=GET
        filters:
        - RewritePath=/api/v1/personal-trainer/addresses, /v1-personal-trainer-crud-addresses
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v1_personal_trainer_read_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer/events
        - Method=GET
        filters:
        - RewritePath=/api/v1/personal-trainer/events, /v1-personal-trainer-crud-events
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v1_personal_trainer_read_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer/subscription-plans
        - Method=GET
        filters:
        - RewritePath=/api/v1/personal-trainer/subscription-plans, /v1-personal-trainer-crud-subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

### student ###

      - id: v1_student_cud_student
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/student
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/student, /v1-student-crud-student
        - name: RoleAuthorization
          args:
            roles: ROLE_STUDENT, ROLE_ADMIN

      - id: v1_student_cud_contacts
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/student/contacts
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/student/contacts, /v1-student-crud-contacts
        - name: RoleAuthorization
          args:
            roles: ROLE_STUDENT, ROLE_ADMIN

      - id: v1_student_cud_addresses
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/student/addresses
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/student/addresses, /v1-student-crud-addresses
        - name: RoleAuthorization
          args:
            roles: ROLE_STUDENT, ROLE_ADMIN

      - id: v1_student_read_student
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/student
        - Method=GET
        filters:
        - RewritePath=/api/v1/student, /v1-student-crud-student
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v1_student_read_contacts
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/student/contacts
        - Method=GET
        filters:
        - RewritePath=/api/v1/student/contacts, /v1-student-crud-contacts
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v1_student_read_addresses
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/student/addresses
        - Method=GET
        filters:
        - RewritePath=/api/v1/student/addresses, /v1-student-crud-addresses
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### sport ###

      - id: v1_sport_cud
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/sport
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/sport, /v1-sport-crud
        - name: RoleAuthorization
          args:
            roles: ROLE_ADMIN

      - id: v1_sport_read
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/sport
        - Method=GET
        filters:
        - RewritePath=/api/v1/sport, /v1-sport-crud
        - name: RoleAuthorization
          args:
            roles: ROLE_USER








### v2 ###







### auth ###

      - id: v2_set_roles
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/set-roles
        - Method=POST
        filters:
        - RewritePath=/api/v2/set-roles, /function-v2/api/v2/set-roles

### gym ###

      - id: v2_cu_gym
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym
        - Method=POST,PUT
        filters:
        - RewritePath=/api/v2/gym, /function-v2/api/v2/gym
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v2_cud_gym_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/events
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/gym/events, /function-v2/api/v2/gym/events
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v2_cud_gym_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/subscription-plans
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/gym/subscription-plans, /function-v2/api/v2/gym/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v2_r_gym
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym
        - Method=GET
        filters:
        - RewritePath=/api/v2/gym, /function-v2/api/v2/gym
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_gym_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/events
        - Method=GET
        filters:
        - RewritePath=/api/v2/gym/events, /function-v2/api/v2/gym/events
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_gym_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/subscription-plans
        - Method=GET
        filters:
        - RewritePath=/api/v2/gym/subscription-plans, /function-v2/api/v2/gym/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### personal trainer ###

      - id: v2_cu_personal_trainer
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer
        - Method=POST,PUT
        filters:
        - RewritePath=/api/v2/personal-trainer, /function-v2/api/v2/personal-trainer
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v2_cud_personal_trainer_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/events
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/personal-trainer/events, /function-v2/api/v2/personal-trainer/events
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v2_cud_personal_trainer_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/subscription-plans
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/personal-trainer/subscription-plans, /function-v2/api/v2/personal-trainer/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v2_r_personal_trainer
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer
        - Method=GET
        filters:
        - RewritePath=/api/v2/personal-trainer, /function-v2/api/v2/personal-trainer
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_personal_trainer_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/events
        - Method=GET
        filters:
        - RewritePath=/api/v2/personal-trainer/events, /function-v2/api/v2/personal-trainer/events
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_personal_trainer_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/subscription-plans
        - Method=GET
        filters:
        - RewritePath=/api/v2/personal-trainer/subscription-plans, /function-v2/api/v2/personal-trainer/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### student ###

      - id: v2_cu_student
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/student
        - Method=POST,PUT
        filters:
        - RewritePath=/api/v2/student, /function-v2/api/v2/student
        - name: RoleAuthorization
          args:
            roles: ROLE_STUDENT, ROLE_ADMIN

      - id: v2_r_student
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/student
        - Method=GET
        filters:
        - RewritePath=/api/v2/student, /function-v2/api/v2/student
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### sport ###

      - id: v2_sport_cud
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/sport
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/sport, /function-v2/api/v2/sport
        - name: RoleAuthorization
          args:
            roles: ROLE_ADMIN

      - id: v2_sport_r
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/sport
        - Method=GET
        filters:
        - RewritePath=/api/v2/sport, /function-v2/api/v2/sport
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### locations ###

      - id: v2_locations
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/locations
        - Method=GET
        filters:
        - RewritePath=/api/v2/locations, /function-v2/api/v2/locations
        - name: RoleAuthorization
          args:
            roles: ROLE_USER
