server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false

spring:
  cloud:
    gateway:
      default-filters:
      - name: KeyIdAuthentication
      - name: ServiceToServiceAuthentication
      routes:

      - id: v1_set_roles
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/set-roles
        - Method=POST
        filters:
        - RewritePath=/api/v1/set-roles, /v1-set-roles

### gym ###

      - id: v1_gym_crud_gym
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/gym, /v1-gym-crud-gym
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v1_gym_crud_contacts
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/contacts
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/gym/contacts, /v1-gym-crud-contacts
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v1_gym_crud_addresses
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/addresses
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/gym/addresses, /v1-gym-crud-addresses
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN
