server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false

spring:
  cloud:
    gateway:
      default-filters:
      - name: KeyIdAuthentication
      - name: ServiceToServiceAuthentication
      routes:

### auth ###

      - id: v2_set_roles
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/set-roles
        - Method=POST
        filters:
        - RewritePath=/api/v2/set-roles, /function-v2/api/v2/set-roles

### gym ###

      - id: v2_cu_gym
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym
        - Method=POST,PUT
        filters:
        - RewritePath=/api/v2/gym, /function-v2/api/v2/gym
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v2_cud_gym_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/events
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/gym/events, /function-v2/api/v2/gym/events
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v2_cud_gym_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/subscription-plans
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/gym/subscription-plans, /function-v2/api/v2/gym/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v2_r_gym
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym
        - Method=GET
        filters:
        - RewritePath=/api/v2/gym, /function-v2/api/v2/gym
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_gym_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/events
        - Method=GET
        filters:
        - RewritePath=/api/v2/gym/events, /function-v2/api/v2/gym/events
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_gym_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/gym/subscription-plans
        - Method=GET
        filters:
        - RewritePath=/api/v2/gym/subscription-plans, /function-v2/api/v2/gym/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### personal trainer ###

      - id: v2_cu_personal_trainer
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer
        - Method=POST,PUT
        filters:
        - RewritePath=/api/v2/personal-trainer, /function-v2/api/v2/personal-trainer
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v2_cud_personal_trainer_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/events
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/personal-trainer/events, /function-v2/api/v2/personal-trainer/events
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v2_cud_personal_trainer_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/subscription-plans
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/personal-trainer/subscription-plans, /function-v2/api/v2/personal-trainer/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v2_r_personal_trainer
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer
        - Method=GET
        filters:
        - RewritePath=/api/v2/personal-trainer, /function-v2/api/v2/personal-trainer
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_personal_trainer_events
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/events
        - Method=GET
        filters:
        - RewritePath=/api/v2/personal-trainer/events, /function-v2/api/v2/personal-trainer/events
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

      - id: v2_r_personal_trainer_subscription_plans
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/personal-trainer/subscription-plans
        - Method=GET
        filters:
        - RewritePath=/api/v2/personal-trainer/subscription-plans, /function-v2/api/v2/personal-trainer/subscription-plans
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### student ###

      - id: v2_cu_student
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/student
        - Method=POST,PUT
        filters:
        - RewritePath=/api/v2/student, /function-v2/api/v2/student
        - name: RoleAuthorization
          args:
            roles: ROLE_STUDENT, ROLE_ADMIN

      - id: v2_r_student
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/student
        - Method=GET
        filters:
        - RewritePath=/api/v2/student, /function-v2/api/v2/student
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### sport ###

      - id: v2_sport_cud
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/sport
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v2/sport, /function-v2/api/v2/sport
        - name: RoleAuthorization
          args:
            roles: ROLE_ADMIN

      - id: v2_sport_r
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/sport
        - Method=GET
        filters:
        - RewritePath=/api/v2/sport, /function-v2/api/v2/sport
        - name: RoleAuthorization
          args:
            roles: ROLE_USER

### focus ###

      - id: v2_focus_cud
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
          - Path=/api/v2/focus
          - Method=POST,PUT,DELETE
        filters:
          - RewritePath=/api/v2/focus, /function-v2/api/v2/focus
          - name: RoleAuthorization
            args:
              roles: ROLE_ADMIN

      - id: v2_focus_r
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
          - Path=/api/v2/focus
          - Method=GET
        filters:
          - RewritePath=/api/v2/focus, /function-v2/api/v2/focus
          - name: RoleAuthorization
            args:
              roles: ROLE_USER

### locations ###

      - id: v2_locations
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v2/locations
        - Method=GET
        filters:
        - RewritePath=/api/v2/locations, /function-v2/api/v2/locations
        - name: RoleAuthorization
          args:
            roles: ROLE_USER
