server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false

spring:
  cloud:
    gateway:
      default-filters:
      - name: KeyIdAuthentication
      - name: ServiceToServiceAuthentication
      routes:

### auth ###

      - id: v1_set_roles
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/set-roles
        - Method=POST
        filters:
        - RewritePath=/api/v1/set-roles, /v1-set-roles

### gym ###

      - id: v1_gym_crud_gym
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/gym, /v1-gym-crud-gym
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v1_gym_crud_contacts
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/contacts
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/gym/contacts, /v1-gym-crud-contacts
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

      - id: v1_gym_crud_addresses
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/gym/addresses
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/gym/addresses, /v1-gym-crud-addresses
        - name: RoleAuthorization
          args:
            roles: ROLE_GYM, ROLE_ADMIN

### personal trainer ###

      - id: v1_personal_trainer_crud_personal-trainer
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/personal-trainer, /v1-personal-trainer-crud-personal-trainer
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v1_personal_trainer_crud_contacts
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer/contacts
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/personal-trainer/contacts, /v1-personal-trainer-crud-contacts
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

      - id: v1_personal_trainer_crud_addresses
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/personal-trainer/addresses
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/personal-trainer/addresses, /v1-personal-trainer-crud-addresses
        - name: RoleAuthorization
          args:
            roles: ROLE_PERSONAL_TRAINER, ROLE_ADMIN

### student ###

      - id: v1_student_crud_student
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/student
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/student, /v1-student-crud-student
        - name: RoleAuthorization
          args:
            roles: ROLE_STUDENT, ROLE_ADMIN

      - id: v1_student_crud_contacts
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/student/contacts
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/student/contacts, /v1-student-crud-contacts
        - name: RoleAuthorization
          args:
            roles: ROLE_STUDENT, ROLE_ADMIN

      - id: v1_student_crud_addresses
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/student/addresses
        - Method=GET,POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/student/addresses, /v1-student-crud-addresses
        - name: RoleAuthorization
          args:
            roles: ROLE_STUDENT, ROLE_ADMIN

### sport ###

      - id: v1_sport_crud
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/sport
        - Method=GET
        filters:
        - RewritePath=/api/v1/sport, /v1-sport-crud

      - id: v1_sport_crud_adm
        uri: ${FITMAP_FUNCTION_URI}
        predicates:
        - Path=/api/v1/sport
        - Method=POST,PUT,DELETE
        filters:
        - RewritePath=/api/v1/sport, /v1-sport-crud
        - name: RoleAuthorization
          args:
            roles: ROLE_ADMIN
