server:
  port: ${PORT}
  error:
    whitelabel:
      enabled: false

spring:
  cloud:
    gateway:
      default-filters:
      - name: KeyIdAuthentication
      - name: ServiceToServiceAuthentication
